name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags: [ "*-v**" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  envmap:
    runs-on: ubuntu-latest
    outputs:
      is_valid: ${{ steps.verify_tag.outputs.is_valid }}
      prefix: ${{ steps.verify_tag.outputs.prefix }}
      version: ${{ steps.verify_tag.outputs.version }}
    steps:
      - name: verify tag
        id: verify_tag
        run: |
          TAG_NAME=${{ github.ref_name }}
          if [[ "$TAG_NAME" =~ ^([a-z]{2})-v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
          COUNTRY=${BASH_REMATCH[1]}
          VERSION=${BASH_REMATCH[2]}
          ENVIRONMENT=prod-$COUNTRY
          echo "$TAG_NAME matches the pattern"
          echo "is_valid=true" >> "$GITHUB_OUTPUT"
          echo "prefix=$PREFIX" >> "$GITHUB_OUTPUT"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          else
          echo "$TAG_NAME does not match the patter"
          echo "is_valid=false" >> "$GITHUB_OUTPUT"
          exit 1
          fi
